" Environment
set viminfofile=NONE

if &compatible
  set nocompatible
endif

if $DEIN_HOME==""
  DEIN_HOME=~/.local/share/dein
endif

" Add the dein installation directory into runtimepath
set runtimepath+=$DEIN_HOME/repos/github.com/Shougo/dein.vim

if dein#load_state('$DEIN_HOME')
  call dein#begin('$DEIN_HOME')

  call dein#add('$DEIN_HOME/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('itchyny/lightline.vim')
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

" lightline
set laststatus=2
