# locale
export LANGUAGE=en_US.UTF-8
export LANG=${LANGUAGE}
export LC_ALL=${LANGUAGE}
export LC_TYPE=${LANGUAGE}

# history
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}"/zsh/history
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt share_history
setopt hist_no_store
setopt hist_reduce_blanks
setopt hist_verify

# zplug
export ZPLUG_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"/zplug
source $ZPLUG_HOME/init.zsh
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-autosuggestions", defer:2
zplug "yous/lime"
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load

# Vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export DEIN_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"/dein

# Homebrew
if [ "$(uname)" = "Linux" ]; then
  HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
elif [ "$(uname -m)" = "arm64" ]; then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

[ -x "${HOMEBREW_PREFIX}"/bin/brew ] && eval "$(${HOMEBREW_PREFIX}/bin/brew shellenv)"

# Starship
[ -x "${HOMEBREW_PREFIX}"/bin/starship ] && eval "$(starship init zsh)"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

function fzf-src() {
  local src=$(ghq list | fzf --height ${FZF_TMUX_HEIGHT:-40%} --reverse )
  zle reset-prompt
  if [ -n "$src" ]; then
    BUFFER="cd $(ghq root)/$src"
    zle accept-line
  fi
  zle -R -c
}
zle -N fzf-src
bindkey '^]' fzf-src
