# locale
export LANGUAGE=en_US.UTF-8
export LANG=${LANGUAGE}
export LC_ALL=${LANGUAGE}
export LC_TYPE=${LANGUAGE}

# history
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}"/zsh/history
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt share_history
setopt hist_no_store
setopt hist_reduce_blanks
setopt hist_verify

# zplug
export ZPLUG_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"/zplug
source $ZPLUG_HOME/init.zsh
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-autosuggestions", defer:2
zplug "yous/lime"
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load

# Vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export DEIN_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"/dein

# fzf
export FZF_CONF="${XDG_CONFIG_HOME:-$HOME/.config}"/fzf
[ -f "${FZF_CONF}"/fzf.zsh ] && source "${FZF_CONF}"/fzf.zsh

function fzf-src() {
  local src=$(ghq list | fzf --height ${FZF_TMUX_HEIGHT:-40%} --reverse )
  zle reset-prompt
  if [ -n "$src" ]; then
    BUFFER="cd $(ghq root)/$src"
    zle accept-line
  fi
  zle -R -c
}
zle -N fzf-src
bindkey '^]' fzf-src

# Homebrew
[ -f /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"

# Starship
[ -e /usr/local/bin/starship ] && eval "$(starship init zsh)"

# Kubernetes: kubectl
if type kubectl >/dev/null 2>&1; then
  source <(kubectl completion zsh)
fi

# nvm - Node Version Manager
export NVM_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"/nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# dvm - Deno Version Manager
export DENO_INSTALL="${XDG_DATA_HOME:-$HOME/.local/share}"/deno
export PATH="$DENO_INSTALL/bin:$PATH"
export DVM_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dvm"
export PATH="$DVM_DIR/bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"
[ -e $HOME/.cargo/env ] && source $HOME/.cargo/env
